"""restaurant table added is public

Revision ID: bb2e1e31a652
Revises: d7dc02732b9d
Create Date: 2019-09-14 12:29:13.180724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb2e1e31a652'
down_revision = 'd7dc02732b9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('is_public', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant', 'is_public')
    # ### end Alembic commands ###
